# Generated by Django 3.0.8 on 2021-01-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackBusiness',
            fields=[
                ('yvonne', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cleaned', models.CharField(blank=True, max_length=30, null=True)),
                ('valid', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=13000, null=True)),
                ('website', models.CharField(blank=True, max_length=10000, null=True)),
                ('title', models.CharField(blank=True, max_length=10300, null=True)),
                ('tags', models.CharField(blank=True, max_length=13000, null=True)),
                ('phone', models.CharField(blank=True, max_length=13000, null=True)),
                ('operation_hours', models.CharField(blank=True, max_length=10000, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=5000, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=5500, null=True)),
                ('email', models.CharField(blank=True, max_length=5000, null=True)),
                ('description', models.CharField(blank=True, max_length=20000, null=True)),
                ('address', models.CharField(blank=True, max_length=30000, null=True)),
                ('source', models.CharField(blank=True, max_length=20000, null=True)),
                ('county', models.CharField(blank=True, max_length=3000, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3000, null=True)),
                ('black_owned', models.CharField(blank=True, max_length=3000, null=True)),
                ('category2', models.CharField(blank=True, max_length=30000, null=True)),
                ('yelp_link', models.CharField(blank=True, max_length=30000, null=True)),
                ('image', models.CharField(blank=True, max_length=200000, null=True)),
                ('social_media', models.CharField(blank=True, max_length=20000, null=True)),
                ('notes', models.CharField(blank=True, max_length=20000, null=True)),
                ('keyword', models.CharField(blank=True, max_length=20000, null=True)),
            ],
        ),
    ]
