# Generated by Django 2.2.17 on 2022-04-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Review'},
        ),
    ]
